version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: psdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  tasks-service:
    build: ./TaskService
    depends_on:
      - db
    environment:
      # В connection string используем имя сервиса 'db'
      DB_CONN: "postgres://postgres:mypassword@db:5432/psdb?sslmode=disable"
    ports:
      - "8080:8080"

  api-gateway:
    build: ./ApiService
    depends_on:
      - tasks-service
    ports:
      - "8000:8000"

volumes:
  pgdata:
